generated_at: '2026-06-17T06:47:19+00:00'
status: pending_review
tables:
- table_name: creditor_export_creditor
  source_file: Creditor.xlsx
  sheet_name: Export_Creditor
  row_count: 523
  column_count: 12
  columns:
  - creditor_extended
  - ref_nr
  - visiting_city
  - fiscal_country
  - contact
  - supplier_code
  - type
  - currency_cred
  - language
  - payment_method
  - payment_terms
  - int_approval
  status: pending_review
- table_name: customerproject_export_customerproject
  source_file: CustomerProject.xlsx
  sheet_name: Export_CustomerProject
  row_count: 1285
  column_count: 12
  columns:
  - ref_nr
  - project_name
  - debtor
  - organisation
  - contact
  - date_contract
  - account_manager
  - sales
  - project_type
  - status
  - financial_status
  - contract_price_costplus
  status: pending_review
- table_name: debtor_export_debtor
  source_file: Debtor.xlsx
  sheet_name: Export_Debtor
  row_count: 215
  column_count: 11
  columns:
  - debtor_extended
  - ref_nr
  - visiting_city_organisation
  - fiscal_country
  - contact_invoice_reminder
  - vat_number
  - currency_debtor
  - language
  - payment_method
  - payment_terms
  - price_list
  status: pending_review
- table_name: deliverynote_export_deliverynote
  source_file: DeliveryNote.xlsx
  sheet_name: Export_DeliveryNote
  row_count: 1893
  column_count: 12
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - print_date
  - period
  - shipping_date
  - project
  - serial_origin
  - references_document
  - transport_by
  - track_n_tracenr
  status: pending_review
- table_name: deliverynoteline
  source_file: DeliveryNoteLine.csv
  sheet_name: ''
  row_count: 4069
  column_count: 17
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - source_sales
  - print_date
  - period
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - tot
  - currency_doc
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  status: pending_review
- table_name: deliverynoteline_export_deliverynoteline
  source_file: DeliveryNoteLine.xlsx
  sheet_name: Export_DeliveryNoteLine
  row_count: 4069
  column_count: 17
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - source_sales
  - print_date
  - period
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - tot
  - currency_doc
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  status: pending_review
- table_name: goodsreception_export_goodsreception
  source_file: GoodsReception.xlsx
  sheet_name: Export_GoodsReception
  row_count: 2564
  column_count: 12
  columns:
  - ref_nr
  - creditor
  - ref_nr_purchase_order
  - receipt_nr_supplier
  - internal_contact
  - stage_gr
  - project
  - internal_keyword
  - organisation_project
  - created_date
  - period
  - remark
  status: pending_review
- table_name: goodsreceptionline_export_goodsreceptionline
  source_file: GoodsReceptionLine.xlsx
  sheet_name: Export_GoodsReceptionLine
  row_count: 4426
  column_count: 13
  columns:
  - ref_nr
  - icon_un_approved
  - period
  - creditor
  - project
  - source_purchase
  - source_sales
  - icon_product
  - suppl_part_nr_sku
  - product_description
  - rec
  - purch_pr_net_p_u
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: organisation_export_organisation
  source_file: Organisation.xlsx
  sheet_name: Export_Organisation
  row_count: 4290
  column_count: 11
  columns:
  - organisation_extended
  - logo
  - ref_nr
  - visiting_city
  - visiting_country
  - deb_no
  - creditor_no
  - phone
  - account_manager
  - engineering
  - status
  status: pending_review
- table_name: product_export_product
  source_file: Product.xlsx
  sheet_name: Export_Product
  row_count: 1734
  column_count: 10
  columns:
  - part_nr_sku
  - suppl_part_nr_sku
  - product_barcode_ce
  - image
  - item_description
  - creditor
  - product_group_name
  - hour_type
  - name
  - gross_sales
  status: pending_review
- table_name: productcomposition_export_productcomposition
  source_file: ProductComposition.xlsx
  sheet_name: Export_ProductComposition
  row_count: 593
  column_count: 4
  columns:
  - part_nr_sku
  - item_description
  - parent_product_code
  - parent_product_description
  status: pending_review
- table_name: productdescription_export_productdescription
  source_file: ProductDescription.xlsx
  sheet_name: Export_ProductDescription
  row_count: 2153
  column_count: 12
  columns:
  - part_nr_sku
  - icon_un_approved
  - image
  - item_description
  - product_group_name
  - icon_phased_out
  - icon_blocked
  - language_descr
  - product_description
  - description_extra_optional_sales
  - specification_code
  - specification_description
  status: pending_review
- table_name: productpricebreak_export_productpricebreak
  source_file: ProductPriceBreak.xlsx
  sheet_name: Export_ProductPriceBreak
  row_count: 3385
  column_count: 17
  columns:
  - type
  - icon_un_approved
  - part_nr_sku
  - image
  - item_description
  - icon_phased_out
  - icon_blocked
  - creditor
  - productgroup
  - icon_stock
  - from
  - up_to
  - techn_stock
  - default
  - currency
  - gr_pur_ex_vat_p_u
  - salesprice
  status: pending_review
- table_name: productsupplier_export_productsupplier
  source_file: ProductSupplier.xlsx
  sheet_name: Export_ProductSupplier
  row_count: 1070
  column_count: 14
  columns:
  - creditor_no
  - creditor
  - part_nr_sku
  - icon_un_approved
  - item_description
  - del_per_pur_days_etd
  - del_per_sales_days
  - from
  - up_to
  - currency
  - gr_pur_ex_vat_p_u
  - discount
  - discount_type_purchase
  - purchase_price_net_unit
  status: pending_review
- table_name: purchaseinvoice
  source_file: PurchaseInvoice.csv
  sheet_name: ''
  row_count: 2844
  column_count: 12
  columns:
  - ref_nr
  - creditor
  - project
  - invoice_nr_suppl
  - date_invoice
  - period
  - approver_purch_inv
  - status_internal
  - tot_pur_ex_vat_cc
  - total_pur_inc_vat_cc
  - due_date
  - not_paid_cc
  status: pending_review
- table_name: purchaseinvoiceline
  source_file: PurchaseInvoiceLine.csv
  sheet_name: ''
  row_count: 6578
  column_count: 14
  columns:
  - ref_nr
  - icon_un_approved
  - creditor
  - project
  - period
  - icon_product
  - suppl_part_nr_sku
  - product_description
  - ledger_purchase_costprice
  - goods_recep_lines_pur
  - qty
  - purch_pr_net_p_u
  - tot_pur_excl_vat
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: purchaseinvoiceline_export_purchaseinvoiceline
  source_file: PurchaseInvoiceLine.xlsx
  sheet_name: Export_PurchaseInvoiceLine
  row_count: 6578
  column_count: 14
  columns:
  - ref_nr
  - icon_un_approved
  - creditor
  - project
  - period
  - icon_product
  - suppl_part_nr_sku
  - product_description
  - ledger_purchase_costprice
  - goods_recep_lines_pur
  - qty
  - purch_pr_net_p_u
  - tot_pur_excl_vat
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: purchaseorder_3_export_purchaseorder
  source_file: PurchaseOrder (3).xlsx
  sheet_name: Export_PurchaseOrder
  row_count: 1994
  column_count: 12
  columns:
  - ref_nr
  - creditor
  - your_reference
  - project
  - order
  - keywords
  - internal_contact
  - int_approval
  - print_date
  - stage_po
  - doc_eta_est_time_of_arr
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: purchaseorderline_export_purchaseorderline
  source_file: PurchaseOrderLine.xlsx
  sheet_name: Export_PurchaseOrderLine
  row_count: 4285
  column_count: 11
  columns:
  - ref_nr
  - icon_un_approved
  - creditor
  - project
  - source_sales
  - icon_product
  - suppl_part_nr_sku
  - product_description
  - qty
  - purch_pr_net_p_u
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: purchaseorderline2_export_purchaseorderline
  source_file: PurchaseOrderLine2.xlsx
  sheet_name: Export_PurchaseOrderLine
  row_count: 4285
  column_count: 15
  columns:
  - doc_ref_nr
  - icon_un_approved
  - creditor
  - project
  - ref_number
  - icon_product
  - part_nr_sku
  - product_description
  - ordered
  - purchase_price_net_unit
  - tot_pur_excl_vat_bought_cc
  - ref_number_1
  - reference_line
  - sales_order_no
  - ref_nr
  status: pending_review
- table_name: purchaseorderline3_export_purchaseorderline
  source_file: PurchaseOrderLine3.xlsx
  sheet_name: Export_PurchaseOrderLine
  row_count: 4285
  column_count: 28
  columns:
  - doc_ref_nr
  - icon_un_approved
  - creditor
  - project
  - ref_number
  - icon_product
  - part_nr_sku
  - product_description
  - ordered
  - purchase_price_net_unit
  - tot_pur_excl_vat_bought_cc
  - ref_number_1
  - reference_line
  - sales_order_no
  - ref_nr
  - creditor_no
  - project_1
  - organisation
  - ref_nr_1
  - reference_nr
  - debtor
  - our_reference
  - part_nr_sku_1
  - ref_nr_2
  - ref_number_2
  - ref_number_3
  - deb_no
  - ref_nr_3
  status: pending_review
- table_name: purchasequotation
  source_file: PurchaseQuotation.csv
  sheet_name: ''
  row_count: 2742
  column_count: 10
  columns:
  - ref_nr
  - creditor
  - project
  - print_date
  - internal_keyword
  - internal_contact
  - approver
  - stage_rfq
  - int_approval
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: purchasequotationline_export_purchasequotationline
  source_file: PurchaseQuotationLine.xlsx
  sheet_name: Export_PurchaseQuotationLine
  row_count: 10965
  column_count: 11
  columns:
  - ref_nr
  - icon_un_approved
  - creditor
  - project
  - source_sales
  - icon_product
  - suppl_part_nr_sku
  - product_description
  - qty
  - purch_pr_net_p_u
  - tot_pur_ex_vat_cc
  status: pending_review
- table_name: salesinvoice
  source_file: SalesInvoice.csv
  sheet_name: ''
  row_count: 2409
  column_count: 12
  columns:
  - ref_nr
  - debtor_no
  - debtor
  - project
  - internal_keyword
  - account_manager
  - invoicedate
  - period
  - tot_sal_ex_vat_cc
  - tot_sal_in_vat_cc
  - paid_cc
  - not_paid_cc
  status: pending_review
- table_name: salesinvoiceline_export_salesinvoiceline
  source_file: SalesInvoiceLine.xlsx
  sheet_name: Export_SalesInvoiceLine
  row_count: 5892
  column_count: 18
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - source_sales
  - origin
  - invoicedate
  - period
  - productgroup
  - part_nr_sku
  - comm_description
  - qty
  - currency
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  - ledger_sales
  status: pending_review
- table_name: salesopportunity
  source_file: SalesOpportunity.csv
  sheet_name: ''
  row_count: 350
  column_count: 14
  columns:
  - ref_nr
  - organisation
  - contact
  - internal_keyword
  - stage
  - type_request
  - status
  - account_manager
  - engineering
  - follow_up
  - lat_foll_up_date
  - tot_ex_vat_cc
  - success_rate
  - weighted_sal_ex_vat_cc
  status: pending_review
- table_name: salesopportunityline_export_salesopportunityline
  source_file: SalesOpportunityLine.xlsx
  sheet_name: Export_SalesOpportunityLine
  row_count: 712
  column_count: 15
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - print_date
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - qty
  - currency
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  status: pending_review
- table_name: salesorder
  source_file: SalesOrder.csv
  sheet_name: ''
  row_count: 1312
  column_count: 19
  columns:
  - ref_nr
  - your_reference
  - concerns
  - remark
  - debtor
  - industry
  - organisation
  - contact
  - project_number_name
  - int_recoq
  - stage
  - am
  - eng
  - eerst_gek_gew_afl_datum
  - eerst_gek_levertijd_weken
  - eerst_gek_ver_afl_datum
  - tot_nett_weight
  - nett_weight
  - tot_sal_ex_vat_cc
  status: pending_review
- table_name: salesorderline
  source_file: SalesOrderLine.csv
  sheet_name: ''
  row_count: 4391
  column_count: 15
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - print_date
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - qty
  - currency_doc
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  status: pending_review
- table_name: salesorderline_export_salesorderline
  source_file: SalesOrderLine.xlsx
  sheet_name: Export_SalesOrderLine
  row_count: 4391
  column_count: 15
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - print_date
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - qty
  - currency_doc
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  status: pending_review
- table_name: salesorderline2_export_salesorderline
  source_file: SalesOrderLine2.xlsx
  sheet_name: Export_SalesOrderLine
  row_count: 4391
  column_count: 80
  columns:
  - doc_ref_nr
  - debtor
  - organisation
  - contact
  - project
  - print_date
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - sold_2_decimal
  - currency_doc
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  - debtor_1
  - hs_code
  - margin
  - part_nr_sku_1
  - product
  - project_1
  - price_per_unit_sales
  - qty
  - company_name
  - creditor
  - invoice_nr_suppl
  - ref_nr
  - supplier_code
  - debtor_2
  - organisation_1
  - ref_nr_1
  - debtor_3
  - debtor_no
  - deb_no
  - debtor_4
  - delivery_city
  - delivery_country
  - our_reference
  - ref_nr_2
  - debtor_5
  - description
  - gr_pur_ex_vat_p_u
  - organisation_2
  - part_nr_sku_2
  - product_1
  - project_2
  - qty_1
  - hs_code_1
  - part_nr_sku_3
  - ref_nr_3
  - sales_pr_net_p_u_1
  - serial_number
  - suppl_part_nr_sku
  - tot_margin
  - creditor_1
  - creditor_no
  - currency_product
  - doc_ref_nr_1
  - part_nr_sku_4
  - ref_number
  - reference_line
  - creditor_no_1
  - creditor_2
  - doc_ref_nr_2
  - part_nr_sku_5
  - product_2
  - product_description
  - project_3
  - ref_number_1
  - debtor_6
  - hs_code_2
  - creation_date
  - deb_no_1
  - deb_country
  - delivery_country_1
  - delivery_city_1
  - description_1
  - our_reference_1
  - organisation_3
  - ref_nr_4
  status: pending_review
- table_name: salesquotation
  source_file: SalesQuotation.csv
  sheet_name: ''
  row_count: 1205
  column_count: 14
  columns:
  - ref_nr
  - organisation
  - contact
  - project
  - keywords
  - type_request
  - stage_sal_quo
  - status_forecast
  - date_possible
  - account_manager
  - engineering
  - tot_sal_ex_vat_cc
  - success_rate
  - weighted_sal_ex_vat_cc
  status: pending_review
- table_name: salesquotationline_export_salesquotationline
  source_file: SalesQuotationLine.xlsx
  sheet_name: Export_SalesQuotationLine
  row_count: 5871
  column_count: 15
  columns:
  - ref_nr
  - debtor
  - organisation
  - contact
  - project
  - print_date
  - productgroup
  - icon_product
  - part_nr_sku
  - comm_description
  - qty
  - currency
  - sales_pr_net_p_u
  - tot_sal_ex_vat
  - tot_sal_ex_vat_cc
  status: pending_review
